
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3305/smartfactory?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: love1994

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/smartfactory?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: love1994

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        default_batch_fetch_size: 100
        #show_sql: true #show sql

  redis:
    host: localhost
    port: 6379

jwt:
  secret-key: eycXTuUMQRajJFMKy8aytRysw0bpQGGpmZyyXkCghh355lq5ZEEHPSO9IOmP
  token-validity-in-sec: 100 # 1??
  refresh-token-validity-in-sec: 604800  # ???
  authorization-header: Authorization


logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

server:
  port: 8060
  servlet:
#    session:
#      tracking-modes: cookie
#      timeout: 1440m
#      cookie:
#        same-site: none
##        http-only: true
#        secure: true

file:
  dir: /Users/khs/Documents/Development/workspace/GBFExcel/

