spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/smartfactory?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: love1994@
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/miraemonitoringsystem?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: love1994

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        default_batch_fetch_size: 100
        #show_sql: true #show sql


logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1440m